/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-07-01 at 17:11:36 UTC 
 * Modify at your own risk.
 */

package com.eduattendanceapp.attendanceendpoint.model;

/**
 * Model definition for Attendance.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the attendanceendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Attendance extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String attendanceId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String className;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String date;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer rollNumber;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String schoolName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String type;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAttendanceId() {
    return attendanceId;
  }

  /**
   * @param attendanceId attendanceId or {@code null} for none
   */
  public Attendance setAttendanceId(java.lang.String attendanceId) {
    this.attendanceId = attendanceId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getClassName() {
    return className;
  }

  /**
   * @param className className or {@code null} for none
   */
  public Attendance setClassName(java.lang.String className) {
    this.className = className;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDate() {
    return date;
  }

  /**
   * @param date date or {@code null} for none
   */
  public Attendance setDate(java.lang.String date) {
    this.date = date;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getRollNumber() {
    return rollNumber;
  }

  /**
   * @param rollNumber rollNumber or {@code null} for none
   */
  public Attendance setRollNumber(java.lang.Integer rollNumber) {
    this.rollNumber = rollNumber;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSchoolName() {
    return schoolName;
  }

  /**
   * @param schoolName schoolName or {@code null} for none
   */
  public Attendance setSchoolName(java.lang.String schoolName) {
    this.schoolName = schoolName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getType() {
    return type;
  }

  /**
   * @param type type or {@code null} for none
   */
  public Attendance setType(java.lang.String type) {
    this.type = type;
    return this;
  }

  @Override
  public Attendance set(String fieldName, Object value) {
    return (Attendance) super.set(fieldName, value);
  }

  @Override
  public Attendance clone() {
    return (Attendance) super.clone();
  }

}
