/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-07-01 at 17:11:36 UTC 
 * Modify at your own risk.
 */

package com.eduattendanceapp.attendanceendpoint;

/**
 * Service definition for Attendanceendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link AttendanceendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Attendanceendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the attendanceendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://attendance-edumust.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "attendanceendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Attendanceendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Attendanceendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getAttendance".
   *
   * This request holds the parameters needed by the attendanceendpoint server.  After setting any
   * optional parameters, call the {@link GetAttendance#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetAttendance getAttendance(java.lang.String id) throws java.io.IOException {
    GetAttendance result = new GetAttendance(id);
    initialize(result);
    return result;
  }

  public class GetAttendance extends AttendanceendpointRequest<com.eduattendanceapp.attendanceendpoint.model.Attendance> {

    private static final String REST_PATH = "attendance/{id}";

    /**
     * Create a request for the method "getAttendance".
     *
     * This request holds the parameters needed by the the attendanceendpoint server.  After setting
     * any optional parameters, call the {@link GetAttendance#execute()} method to invoke the remote
     * operation. <p> {@link GetAttendance#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetAttendance(java.lang.String id) {
      super(Attendanceendpoint.this, "GET", REST_PATH, null, com.eduattendanceapp.attendanceendpoint.model.Attendance.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetAttendance setAlt(java.lang.String alt) {
      return (GetAttendance) super.setAlt(alt);
    }

    @Override
    public GetAttendance setFields(java.lang.String fields) {
      return (GetAttendance) super.setFields(fields);
    }

    @Override
    public GetAttendance setKey(java.lang.String key) {
      return (GetAttendance) super.setKey(key);
    }

    @Override
    public GetAttendance setOauthToken(java.lang.String oauthToken) {
      return (GetAttendance) super.setOauthToken(oauthToken);
    }

    @Override
    public GetAttendance setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetAttendance) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetAttendance setQuotaUser(java.lang.String quotaUser) {
      return (GetAttendance) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetAttendance setUserIp(java.lang.String userIp) {
      return (GetAttendance) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetAttendance setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetAttendance set(String parameterName, Object value) {
      return (GetAttendance) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertAttendance".
   *
   * This request holds the parameters needed by the attendanceendpoint server.  After setting any
   * optional parameters, call the {@link InsertAttendance#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.eduattendanceapp.attendanceendpoint.model.Attendance}
   * @return the request
   */
  public InsertAttendance insertAttendance(com.eduattendanceapp.attendanceendpoint.model.Attendance content) throws java.io.IOException {
    InsertAttendance result = new InsertAttendance(content);
    initialize(result);
    return result;
  }

  public class InsertAttendance extends AttendanceendpointRequest<com.eduattendanceapp.attendanceendpoint.model.Attendance> {

    private static final String REST_PATH = "attendance";

    /**
     * Create a request for the method "insertAttendance".
     *
     * This request holds the parameters needed by the the attendanceendpoint server.  After setting
     * any optional parameters, call the {@link InsertAttendance#execute()} method to invoke the
     * remote operation. <p> {@link InsertAttendance#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.eduattendanceapp.attendanceendpoint.model.Attendance}
     * @since 1.13
     */
    protected InsertAttendance(com.eduattendanceapp.attendanceendpoint.model.Attendance content) {
      super(Attendanceendpoint.this, "POST", REST_PATH, content, com.eduattendanceapp.attendanceendpoint.model.Attendance.class);
    }

    @Override
    public InsertAttendance setAlt(java.lang.String alt) {
      return (InsertAttendance) super.setAlt(alt);
    }

    @Override
    public InsertAttendance setFields(java.lang.String fields) {
      return (InsertAttendance) super.setFields(fields);
    }

    @Override
    public InsertAttendance setKey(java.lang.String key) {
      return (InsertAttendance) super.setKey(key);
    }

    @Override
    public InsertAttendance setOauthToken(java.lang.String oauthToken) {
      return (InsertAttendance) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertAttendance setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertAttendance) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertAttendance setQuotaUser(java.lang.String quotaUser) {
      return (InsertAttendance) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertAttendance setUserIp(java.lang.String userIp) {
      return (InsertAttendance) super.setUserIp(userIp);
    }

    @Override
    public InsertAttendance set(String parameterName, Object value) {
      return (InsertAttendance) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listAttendance".
   *
   * This request holds the parameters needed by the attendanceendpoint server.  After setting any
   * optional parameters, call the {@link ListAttendance#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListAttendance listAttendance() throws java.io.IOException {
    ListAttendance result = new ListAttendance();
    initialize(result);
    return result;
  }

  public class ListAttendance extends AttendanceendpointRequest<com.eduattendanceapp.attendanceendpoint.model.CollectionResponseAttendance> {

    private static final String REST_PATH = "attendance";

    /**
     * Create a request for the method "listAttendance".
     *
     * This request holds the parameters needed by the the attendanceendpoint server.  After setting
     * any optional parameters, call the {@link ListAttendance#execute()} method to invoke the remote
     * operation. <p> {@link ListAttendance#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListAttendance() {
      super(Attendanceendpoint.this, "GET", REST_PATH, null, com.eduattendanceapp.attendanceendpoint.model.CollectionResponseAttendance.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListAttendance setAlt(java.lang.String alt) {
      return (ListAttendance) super.setAlt(alt);
    }

    @Override
    public ListAttendance setFields(java.lang.String fields) {
      return (ListAttendance) super.setFields(fields);
    }

    @Override
    public ListAttendance setKey(java.lang.String key) {
      return (ListAttendance) super.setKey(key);
    }

    @Override
    public ListAttendance setOauthToken(java.lang.String oauthToken) {
      return (ListAttendance) super.setOauthToken(oauthToken);
    }

    @Override
    public ListAttendance setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListAttendance) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListAttendance setQuotaUser(java.lang.String quotaUser) {
      return (ListAttendance) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListAttendance setUserIp(java.lang.String userIp) {
      return (ListAttendance) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListAttendance setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListAttendance setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListAttendance set(String parameterName, Object value) {
      return (ListAttendance) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeAttendance".
   *
   * This request holds the parameters needed by the attendanceendpoint server.  After setting any
   * optional parameters, call the {@link RemoveAttendance#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveAttendance removeAttendance(java.lang.String id) throws java.io.IOException {
    RemoveAttendance result = new RemoveAttendance(id);
    initialize(result);
    return result;
  }

  public class RemoveAttendance extends AttendanceendpointRequest<Void> {

    private static final String REST_PATH = "attendance/{id}";

    /**
     * Create a request for the method "removeAttendance".
     *
     * This request holds the parameters needed by the the attendanceendpoint server.  After setting
     * any optional parameters, call the {@link RemoveAttendance#execute()} method to invoke the
     * remote operation. <p> {@link RemoveAttendance#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveAttendance(java.lang.String id) {
      super(Attendanceendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveAttendance setAlt(java.lang.String alt) {
      return (RemoveAttendance) super.setAlt(alt);
    }

    @Override
    public RemoveAttendance setFields(java.lang.String fields) {
      return (RemoveAttendance) super.setFields(fields);
    }

    @Override
    public RemoveAttendance setKey(java.lang.String key) {
      return (RemoveAttendance) super.setKey(key);
    }

    @Override
    public RemoveAttendance setOauthToken(java.lang.String oauthToken) {
      return (RemoveAttendance) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveAttendance setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveAttendance) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveAttendance setQuotaUser(java.lang.String quotaUser) {
      return (RemoveAttendance) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveAttendance setUserIp(java.lang.String userIp) {
      return (RemoveAttendance) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveAttendance setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveAttendance set(String parameterName, Object value) {
      return (RemoveAttendance) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateAttendance".
   *
   * This request holds the parameters needed by the attendanceendpoint server.  After setting any
   * optional parameters, call the {@link UpdateAttendance#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.eduattendanceapp.attendanceendpoint.model.Attendance}
   * @return the request
   */
  public UpdateAttendance updateAttendance(com.eduattendanceapp.attendanceendpoint.model.Attendance content) throws java.io.IOException {
    UpdateAttendance result = new UpdateAttendance(content);
    initialize(result);
    return result;
  }

  public class UpdateAttendance extends AttendanceendpointRequest<com.eduattendanceapp.attendanceendpoint.model.Attendance> {

    private static final String REST_PATH = "attendance";

    /**
     * Create a request for the method "updateAttendance".
     *
     * This request holds the parameters needed by the the attendanceendpoint server.  After setting
     * any optional parameters, call the {@link UpdateAttendance#execute()} method to invoke the
     * remote operation. <p> {@link UpdateAttendance#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.eduattendanceapp.attendanceendpoint.model.Attendance}
     * @since 1.13
     */
    protected UpdateAttendance(com.eduattendanceapp.attendanceendpoint.model.Attendance content) {
      super(Attendanceendpoint.this, "PUT", REST_PATH, content, com.eduattendanceapp.attendanceendpoint.model.Attendance.class);
    }

    @Override
    public UpdateAttendance setAlt(java.lang.String alt) {
      return (UpdateAttendance) super.setAlt(alt);
    }

    @Override
    public UpdateAttendance setFields(java.lang.String fields) {
      return (UpdateAttendance) super.setFields(fields);
    }

    @Override
    public UpdateAttendance setKey(java.lang.String key) {
      return (UpdateAttendance) super.setKey(key);
    }

    @Override
    public UpdateAttendance setOauthToken(java.lang.String oauthToken) {
      return (UpdateAttendance) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateAttendance setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateAttendance) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateAttendance setQuotaUser(java.lang.String quotaUser) {
      return (UpdateAttendance) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateAttendance setUserIp(java.lang.String userIp) {
      return (UpdateAttendance) super.setUserIp(userIp);
    }

    @Override
    public UpdateAttendance set(String parameterName, Object value) {
      return (UpdateAttendance) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Attendanceendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Attendanceendpoint}. */
    @Override
    public Attendanceendpoint build() {
      return new Attendanceendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link AttendanceendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setAttendanceendpointRequestInitializer(
        AttendanceendpointRequestInitializer attendanceendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(attendanceendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
